CC  = fcc
CXX = FCC
FC  = frt
LINKER = $(CC)

ANSI_CFLAGS  = 

CFLAGS   = -O2 -std=c99 -fPIC -g -Wall $(ANSI_CFLAGS)
CXXFLAGS = $(CFLAGS)
FCFLAGS  = -J ./$(TAG)
VERSION  = -v
LFLAGS   =
DEFINES  = -D_GNU_SOURCE
INCLUDES =
LIBS     =
