# Supported: GCC, CLANG, ICC
TAG ?= CLANG
ENABLE_OPENMP ?= false
ENABLE_LIKWID ?= false

#Feature options
OPTIONS  =  -DSIZE=120000000ull
OPTIONS +=  -DARRAY_ALIGNMENT=64
# OPTIONS +=  -DVERBOSE_DATASIZE
# OPTIONS +=  -DVERBOSE_TIMER
